name: 'Verify Terraform modules'

on:
  pull_request:

permissions:
  contents: read

jobs:
  verify:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: "Setup terraform"
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.9.5"

      - name: "Verify"
        run: sh dev-tools/validate.sh